Exploración inicial
Importamos pandas con un alias, y le decimos que lea el dataset. Le decimos con shape que nos digas cuántas filas y columnas tiene.

In [1]:
import pandas as pd

df = pd.read_csv('../data/raw/jobs_in_data.csv')
df.shape

(9355, 12)

Ahora mostramos las primeras 5 filas del dataset. (Con df.tail (5) veríamos las últimas).

In [2]:
df.head()

,work_year,job_title,job_category,salary_currency,salary,salary_in_usd,employee_residence,experience_level,employment_type,work_setting,company_location,company_size
0,2023,Data DevOps Engineer,Data Engineering,EUR,88000,95012,Germany,Mid-level,Full-time,Hybrid,Germany,L
1,2023,Data Architect,Data Architecture and Modeling,USD,186000,186000,United States,Senior,Full-time,In-person,United States,M
2,2023,Data Architect,Data Architecture and Modeling,USD,81800,81800,United States,Senior,Full-time,In-person,United States,M
3,2023,Data Scientist,Data Science and Research,USD,212000,212000,United States,Senior,Full-time,In-person,United States,M
4,2023,Data Scientist,Data Science and Research,USD,93300,93300,United States,Senior,Full-time,In-person,United States,M

Mostramos tipos de datos

In [3]:
df.dtypes

work_year             int64
job_title               str
job_category            str
salary_currency         str
salary                int64
salary_in_usd         int64
employee_residence      str
experience_level        str
employment_type         str
work_setting            str
company_location        str
company_size            str
dtype: object

Estadísticas básicas. Aquí nos da estadísticas para cada columna numérica: count (cuántos valores no nulos hay), mean (media aritmética), std (desviación estándar), min (Valor mínimo), 25% (Percentil 25, el 25% de los datos está por debajo de este valor), mediana (valor central del dataset), Percentil 75 (el 75% de los datos está por debajo de este valor), max (valor máximo).

In [4]:
df.describe()

         work_year         salary  salary_in_usd
count  9355.000000    9355.000000    9355.000000
mean   2022.760449  149927.981293  150299.495564
std       0.519470   63608.835387   63177.372024
min    2020.000000   14000.000000   15000.000000
25%    2023.000000  105200.000000  105700.000000
50%    2023.000000  143860.000000  143000.000000
75%    2023.000000  187000.000000  186723.000000
max    2023.000000  450000.000000  450000.000000

Lectura de resultados actual: El dataset cubre 2020 a 2023 (min/max de work_year). El salario medio es $150.299 — bastante alto. El mínimo es $15.000 y el máximo $450.000 — hay una dispersión enorme. El 75% de los registros está por debajo de $186.723, pero el máximo llega a $450k — esos valores extremos son outliers.